# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_builtins.py`

{# TODO: GDString ~ String #}
{% for item in specs %}

class {{item.name}}:
{% if not item.methods or item.constants %}
    ...
{% else %}
{%for i in item.constants %}
    {{i.name}}: {{i.type.name}}
{% endfor %}
{%for i in item.methods %}
    def {{i.name}}(self{% for a in i.arguments %}, {{a.name}}: {{ a.type.name }}{% endfor %}) -> {{i.return_type.name}}: ...
{% endfor %}
{% endif %}

{% endfor %}

