# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_builtins.py`


class GDObject:
    ...


GDVariant = None | GDObject | {{ specs | map(attribute="name") | join(" | ") }}

{% macro render_arg(arg) -%}
{{arg.name}}: {{ arg.type.name if arg.type.name != "GDString" else "GDString | str"}}{{ "={}".format(arg.default_value) if arg.default_value is not none }}
{%- endmacro %}

{% for spec in specs %}

class {{spec.name}}:
{% for c in spec.constructors %}
    def __init__(self{% for a in c.arguments %}, {{ render_arg(a) }}{% endfor %}): ...
{% endfor %}
{% if spec.members %}
    # Members
{% endif %}
{% for m in spec.members %}
    {{m.name}}: {{ m.type.name }}
{% endfor %}
{% if spec.methods %}
    # Methods
{% endif %}
{% for m in spec.methods %}
    def {{m.name}}(self{% for a in m.arguments %}, {{ render_arg(a) }}{% endfor %}) -> {{ m.return_type.name if m.return_type is not none else "None" }}: ...
{% endfor %}
{% if spec.constants %}
    # Constants
{% endif %}
{% for c in spec.constants %}
    {{c.name}}: {{c.type.name}}
{% endfor %}

{% endfor %}
