# /!\ Autogenerated code, modifications will be lost /!\
# see `scripts/generate_tmpl.py`

cimport cython
{% for spec in api["builtins"] if not spec.is_scalar %}


@cython.freelist(8)
@cython.final
cdef class {{ spec.name }}:
    cdef char _gd_data[{{ spec.size }}]

    @staticmethod
    cdef inline {{ spec.name }} new()
{% endfor %}
