repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:

    - id: mixed-line-ending

    - id: trailing-whitespace
      exclude: ^tests/.*/expected.output

-   repo: local
    hooks:

    - id: git_actions_pin
      name: "Gitub actions pin 3rd party repos"
      entry: python ./misc/pin_github_actions.py check
      language: python
      language_version: python3
      files: ^.github/

    - id: lint
      name: lint (using `uvx ruff check`)
      entry: uvx ruff check --fix
      require_serial: true
      language: system
      types_or: [python, pyi]

    - id: format
      name: format (using `uvx ruff format`)
      entry: uvx ruff format
      require_serial: true
      language: system
      types_or: [python, pyi]
      args: [--config=pyproject.toml]
