# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_builtins.py`

from typing import Union


class AABB:
	pass

class Array:
	pass

class Basis:
	pass

class Color:
	pass

class Dictionary:
	pass

class NodePath:
	pass

class Plane:
	pass

class Quat:
	pass

class Rect2:
	pass

class RID:
	pass

class Transform2D:
	pass

class Transform:
	pass

class Vector2:
	pass

class Vector3:
	pass

class PoolByteArray:
	pass

class PoolIntArray:
	pass

class PoolRealArray:
	pass

class PoolStringArray:
	pass

class PoolVector2Array:
	pass

class PoolVector3Array:
	pass

class PoolColorArray:
	pass

class GDString:
	pass

{% set render_target = "rid" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "vector3" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "vector2" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "aabb" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "basis" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "color" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "gdstring" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "rect2" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "transform2d" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "plane" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "quat" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "transform" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "node_path" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "dictionary" %}
{% include 'render.tmpl.pyi' with context  %}
