# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_builtins.py`

from typing import Union

{% set render_target = "rid" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "vector3" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "vector2" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "aabb" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "basis" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "color" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "gdstring" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "rect2" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "transform2d" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "plane" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "quat" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "transform" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "node_path" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "dictionary" %}
{% include 'render.tmpl.pyi' with context  %}
{% set render_target = "array" %}
{% include 'render.tmpl.pyi' with context  %}
