# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_builtins.py`

from typing import Union

cimport cython

from godot._hazmat.gdnative_api_struct cimport *
from godot._hazmat.gdapi cimport (
    pythonscript_gdapi10 as gdapi10,
    pythonscript_gdapi11 as gdapi11,
    pythonscript_gdapi12 as gdapi12,
)
from godot._hazmat.conversion cimport *
from godot.pool_arrays cimport (
    PoolIntArray,
    PoolRealArray,
    PoolByteArray,
    PoolVector2Array,
    PoolVector3Array,
    PoolColorArray,
    PoolStringArray,
)

{% set render_target = "rid" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "vector3" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "vector2" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "aabb" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "basis" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "color" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "gdstring" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "rect2" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "transform2d" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "plane" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "quat" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "transform" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "node_path" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "dictionary" %}
{% include 'render.tmpl.pyx' with context  %}
{% set render_target = "array" %}
{% include 'render.tmpl.pyx' with context  %}
