# /!\ Autogenerated code, modifications will be lost /!\
# see `tools/generate_bindings.py`

from godot._hazmat.gdnative_api_struct cimport *
from godot._hazmat.gdapi cimport pythonscript_gdapi as gdapi
from godot._hazmat.conversion cimport *
from godot.aabb cimport AABB
from godot.array cimport Array
from godot.basis cimport Basis
from godot.color cimport Color
from godot.dictionary cimport Dictionary
from godot.node_path cimport NodePath
from godot.plane cimport Plane
from godot.quat cimport Quat
from godot.rect2 cimport Rect2
from godot.rid cimport RID
from godot.transform cimport Transform
from godot.transform2d cimport Transform2D
from godot.vector2 cimport Vector2
from godot.vector3 cimport Vector3
from godot.pool_arrays cimport (
    PoolIntArray,
    PoolRealArray,
    PoolByteArray,
    PoolVector2Array,
    PoolVector3Array,
    PoolColorArray,
    PoolStringArray,
)

### Classes ###

{% include "classes.tmpl.pyx" %}

### Singletons ###

{% include "singletons.tmpl.pyx" %}

### Global constants ###

{% include "global_constants.tmpl.pyx" %}
