# /!\ Autogenerated code, modifications will be lost /!\
# see `tools/generate_bindings.py`

from godot.hazmat.gdnative_api_struct cimport *
from godot.hazmat._gdapi cimport pythonscript_gdapi as gdapi

### Classes ###

{% include "classes.tmpl.pyx" %}

### Singletons ###

{% include "singletons.tmpl.pyx" %}

### Global constants ###

{% include "global_constants.tmpl.pyx" %}
