# /!\ Autogenerated code, modifications will be lost /!\
# see `tools/generate_bindings.py`

from godot._hazmat.gdnative_api_struct cimport *
from godot._hazmat.gdapi cimport pythonscript_gdapi10 as gdapi10
from godot._hazmat.conversion cimport *
from godot.builtins cimport *
{% for part in range(nb_parts) %}
from godot.bindings_part{{ part }} cimport *
{% endfor %}

{% from 'class.tmpl.pyx' import render_class -%}
{%- for cls in classes %}
{{ render_class(cls) }}
{%- endfor -%}
