import argparse
import textwrap
from pathlib import Path
import re
from dataclasses import dataclass


PRAGMA_RE = re.compile(r"^(?P<indentation>\s*)# godot_extension:\s+(?P<pragma>.*)$")
CLASS_RE = re.compile(r"^cdef class (?P<class_name>\w+)")
METHOD_RE = re.compile(
    r"^cdef\s+(inline\s+)?(?P<return_type>\w+((\s*\*\s*)|(\s+)))(?P<method_name>\w+)\((?P<parameters>.*)\):"
)

INJECT_CLASS_CODE_PRAGMA = "generate_class_code()"
INJECT_MODULE_CODE_PRAGMA = "generate_module_code()"
AUTOGENERATED_HEADER = "*** Start of auto-generated code ***"
AUTOGENERATED_FOOTER = "*** End of auto-generated code ***"


@dataclass(slots=True)
class MethodDef:
    method_name: str
    is_staticmethod: bool
    is_const: bool
    is_virtual: bool
    return_type: str
    parameters: dict[str, str]


@dataclass(slots=True)
class ClassDef:
    class_def_at_line: int
    class_name: str
    parent_class_name: str
    is_virtual: bool
    is_abstract: bool
    is_exposed: bool
    methods: list[MethodDef]
    inject_code_at_line: int
    register_class_hook: str | None
    unregister_class_hook: str | None
    cinit_instance_hook: str | None
    free_instance_hook: str | None


@dataclass(slots=True)
class ModuleDef:
    inject_module_code_at_line: int
    classes: list[ClassDef]


def generate_injected_class_code_method(
    spec: MethodDef, class_spec: ClassDef, virtual_flavor: bool = False
) -> str:
    code = f"""
@staticmethod
cdef void __godot_extension_class_{"virtual_" if virtual_flavor else ""}meth_{spec.method_name}(
    {"void *method_userdata," if not virtual_flavor else ""}
    GDExtensionClassInstancePtr p_instance,
    const GDExtensionConstTypePtr *p_args,
    GDExtensionTypePtr r_ret,
) noexcept with gil:
"""
    if class_spec.class_name != "PythonScriptLanguage" or spec.method_name != "_frame":
        code += f"""
    # print("[DEBUG] {class_spec.class_name}.__godot_extension_class_{"virtual_" if virtual_flavor else ""}meth_{spec.method_name}()")
"""

    if spec.return_type == "void":
        code += "    "
    else:
        code += f"    (<{spec.return_type}*>r_ret)[0] = "
    if spec.is_staticmethod:
        code += f"{class_spec.class_name}.{spec.method_name}("
    else:
        code += f"(<{class_spec.class_name}>p_instance).{spec.method_name}("

    if len(spec.parameters) == 0:
        code += ")"
    else:
        code += "\n"
        for i, (_, param_type) in enumerate(spec.parameters.items()):
            code += f"        (<{param_type}*>p_args[{i}])[0],\n"
        code += "    )\n"

    if spec.is_virtual and not virtual_flavor:
        code += "\n"
        code += generate_injected_class_code_method(spec, class_spec, virtual_flavor=True)

    return code


def generate_injected_class_code_register(spec: ClassDef) -> str:
    code = f"""

def __cinit__(self):
    self._gd_ptr = gdptrs.gdptr_classdb_construct_object(&__godot_extension_{spec.class_name}_parent_class_name)
    gdptrs.gdptr_object_set_instance(
        self._gd_ptr,
        &__godot_extension_{spec.class_name}_class_name,
        <PyObject*>self
    )
    # Since we have registered this Python object into a Godot class instance, we must
    # make sure the Python object won't be destroyed before the Godot class instance.
    # Hence this manual refcount increase that will be decreased when Godot class
    # instance's `free()` method is called (see `__godot_extension_free_instance`).
    Py_INCREF(self)
    {spec.class_name + "." + spec.cinit_instance_hook + "()" if spec.cinit_instance_hook is not None else ""}

@staticmethod
cdef GDExtensionObjectPtr __godot_extension_create_instance(void* p_class_userdata) noexcept with gil:
    # print("[DEBUG] {spec.class_name}.__godot_extension_create_instance()")
    cdef {spec.class_name} obj = {spec.class_name}()
    # Note `Py_INCREF(obj)` has already been done during `__cinit__`
    return obj._gd_ptr

@staticmethod
cdef void __godot_extension_free_instance(void* p_class_userdata, GDExtensionClassInstancePtr p_instance) noexcept with gil:
    # print("[DEBUG] {spec.class_name}.__godot_extension_free_instance()")
    {spec.class_name + "." + spec.free_instance_hook + "()" if spec.free_instance_hook is not None else ""}
    Py_DECREF(<{spec.class_name}>p_instance)

@staticmethod
def __godot_extension_unregister_class():
    # print("[DEBUG] {spec.class_name}.__godot_extension_unregister_class()")

    global __godot_extension_{spec.class_name}_registered
    if not __godot_extension_{spec.class_name}_registered:
        print("Not registered !", flush=True)
        raise RuntimeError("Not registered !")

    {spec.class_name + "." + spec.unregister_class_hook + "()" if spec.unregister_class_hook is not None else ""}
    unregister_extension_class(b"{spec.class_name}")
    gd_string_name_del(&__godot_extension_{spec.class_name}_class_name)
    gd_string_name_del(&__godot_extension_{spec.class_name}_parent_class_name)

    __godot_extension_{spec.class_name}_registered = False

@staticmethod
def __godot_extension_register_class():
    # print("[DEBUG] {spec.class_name}.__godot_extension_register_class()")

    global __godot_extension_{spec.class_name}_registered
    if __godot_extension_{spec.class_name}_registered:
        print("Already registered !", flush=True)
        raise RuntimeError("Already registered !")

    global __godot_extension_{spec.class_name}_class_name
    global __godot_extension_{spec.class_name}_parent_class_name
    __godot_extension_{spec.class_name}_class_name = gd_string_name_from_unchecked_pystr("{spec.class_name}")
    __godot_extension_{spec.class_name}_parent_class_name = gd_string_name_from_unchecked_pystr("{spec.parent_class_name}")

    register_extension_class_creation(
        b"{spec.class_name}",
        b"{spec.parent_class_name}",
        &{spec.class_name}.__godot_extension_create_instance,
        &{spec.class_name}.__godot_extension_free_instance,
        &{spec.class_name}.__godot_extension_get_virtual,
        {"True" if spec.is_virtual else "False"},
        {"True" if spec.is_abstract else "False"},
        {"True" if spec.is_exposed else "False"},
    )

    __godot_extension_{spec.class_name}_registered = True
"""
    for method in spec.methods:
        cooked_params = "["
        for param_name, param_type in method.parameters.items():
            cooked_params += "("
            cooked_params += f'b"{param_name}", b"{param_type}"'
            cooked_params += "), "
        cooked_params += "]"

        code += textwrap.indent(
            f"""
register_extension_class_method(
    b"{spec.class_name}",
    b"{method.method_name}",
    &{spec.class_name}.__godot_extension_class_meth_{method.method_name},
    {"True" if method.is_staticmethod else "False"},
    b"{method.return_type}",
    {cooked_params}
)
""",
            prefix="    ",
        )

    # TODO: cache virtual methods name to avoid pystr to gd_string_name_t conversions
    code += """
@staticmethod
cdef GDExtensionClassCallVirtual __godot_extension_get_virtual(void *p_class_userdata, GDExtensionConstStringNamePtr p_name) noexcept with gil:
    cdef gd_string_t gd_candidate_name
"""
    code += f"""
    # print("[DEBUG] {spec.class_name}.__godot_extension_get_virtual()")
"""

    for method in spec.methods:
        if not method.is_virtual:
            continue
        code += f"""
    gd_candidate_name = gd_string_from_pybytes(b"{method.method_name}")
    if gd_string_name_op_equal_string(<const gd_string_name_t *>p_name, &gd_candidate_name):
        gd_string_del(&gd_candidate_name)
        return &{spec.class_name}.__godot_extension_class_virtual_meth_{method.method_name}
    gd_string_del(&gd_candidate_name)
"""

    code += f"""
    {spec.class_name + "." + spec.register_class_hook + "()" if spec.register_class_hook is not None else ""}
    return NULL
"""

    return code


def generate_injected_class_code(spec: ClassDef) -> str:
    code = ""

    for method_spec in spec.methods:
        method_code = generate_injected_class_code_method(method_spec, spec)
        code += textwrap.indent(method_code, prefix="    ")

    register_code = generate_injected_class_code_register(spec)
    code += textwrap.indent(register_code, prefix="    ")

    return code


def generate_injected_module_code(spec: ModuleDef) -> str:
    code = ""

    for klass in spec.classes:
        code += f"""
# {klass.class_name}
cdef bint __godot_extension_{klass.class_name}_registered = False
cdef gd_string_name_t __godot_extension_{klass.class_name}_class_name
cdef gd_string_name_t __godot_extension_{klass.class_name}_parent_class_name
"""

    return code


def handle_pointer_type(raw_type: str) -> str:
    # Type is not a real Godot object, but we still use `gd_object_t`
    # to represent the fact it is a pointer
    try:
        pointed_type, expect_star = raw_type.split()
        if not expect_star != "*":
            raise RuntimeError(f"bad type `{raw_type}`, expected `<type>` or `<type> *`")
        return f"{pointed_type}*"
    except ValueError:
        return raw_type.strip()


def extract_classes_from_code(raw_code_lines: list[str]) -> ModuleDef:
    code_lines = enumerate(raw_code_lines)
    classes: list[ClassDef] = []
    inject_module_code_at_line: int = -1

    current_class: ClassDef | None = None
    for i, line in code_lines:
        match = PRAGMA_RE.match(line)
        if not match:
            continue

        pragma = match.group("pragma").strip()
        if pragma == INJECT_CLASS_CODE_PRAGMA:
            if current_class is None:
                raise RuntimeError(
                    f"Line {i + 1}: `# godot_extension: {pragma}` must be within a `# godot_extension: class(...)` pragma"
                )

            if current_class.inject_code_at_line != -1:
                raise RuntimeError(
                    f"Line {i + 1}: `# godot_extension: {pragma}` already defined at line {current_class.inject_code_site} for class `{current_class.class_name}`"
                )

            current_class.inject_code_at_line = i

        elif pragma == INJECT_MODULE_CODE_PRAGMA:
            if not line.startswith("#"):  # Detect unexpected indentation
                raise RuntimeError(
                    f"Line {i + 1}: `# godot_extension: {pragma}` must be at module level (i.e. not within class/function definition)"
                )

            if inject_module_code_at_line != -1:
                raise RuntimeError(
                    f"Line {i + 1}: `# godot_extension: {pragma}` already defined at line {inject_module_code_at_line}"
                )

            inject_module_code_at_line = i

        elif pragma in (AUTOGENERATED_HEADER, AUTOGENERATED_FOOTER):
            continue

        else:

            def _collect_method_signature() -> MethodDef:
                try:
                    _, line = next(code_lines)
                    is_staticmethod = line.strip() == "@staticmethod"
                    if is_staticmethod:
                        _, line = next(code_lines)
                except StopIteration:
                    raise RuntimeError("unexpected end of file")

                if line.strip().startswith("@"):
                    raise RuntimeError("Only `@staticmethod` decorator is supported")

                # Retrieve the parameters that can span accross multiple lines
                try:
                    current_line = iter(line[line.index("(") + 1 :])
                    meth_signature = line[: line.index("(") + 1].strip()
                except ValueError:
                    raise RuntimeError(
                        f"expected method signature `cdef [inline] (gd_xxx_t|void) foo({'' if is_staticmethod else 'self, '}gd_yyy_t bar, ...)`"
                    )
                open_parenthesises = 1
                while open_parenthesises > 0:
                    for c in current_line:
                        if c == "(":
                            open_parenthesises += 1
                        elif c == ")":
                            open_parenthesises -= 1
                        meth_signature += c
                    if open_parenthesises:
                        try:
                            _, current_line = next(code_lines)
                        except StopIteration:
                            raise RuntimeError("unexpected end of file")

                match = METHOD_RE.match(meth_signature)
                if not match:
                    raise RuntimeError(
                        f"expected method signature `cdef [inline] (gd_xxx_t|void) foo({'' if is_staticmethod else 'self, '}gd_yyy_t bar, ...)`"
                    )

                return_type = handle_pointer_type(match.group("return_type"))

                params = {}
                raw_params = match.group("parameters").strip()
                if raw_params:

                    def _strip_py_typing(x: str) -> str:
                        return x.split(":", 1)[0].strip()

                    for i, raw_param in enumerate(
                        y for x in raw_params.split(",") if (y := _strip_py_typing(x))
                    ):
                        raw_param = raw_param.split(":", 1)[0].strip()
                        if not raw_param:
                            continue

                        if i == 0 and not is_staticmethod:
                            if raw_param != "self":
                                raise RuntimeError(
                                    "expected first paramater for non static method to be `self`"
                                )
                            continue

                        try:
                            param_type, param_name = raw_param.split()
                        except ValueError:
                            raise RuntimeError(f"bad parameter {raw_param!r}")
                        params[param_name] = handle_pointer_type(param_type)

                return MethodDef(
                    is_staticmethod=is_staticmethod,
                    method_name=match.group("method_name"),
                    return_type=return_type,
                    parameters=params,
                    is_const=False,
                    is_virtual=False,
                )

            def _register_class_hook() -> None:
                if current_class is None:
                    raise RuntimeError(
                        "`# godot_extension: register_class_hook` must be within a `# godot_extension: class(...)` pragma"
                    )

                if current_class.register_class_hook is not None:
                    raise RuntimeError(
                        "`# godot_extension: register_class_hook` can only be set once per `# godot_extension: class(...)` pragma"
                    )

                signature = _collect_method_signature()
                if not signature.is_staticmethod:
                    raise RuntimeError(
                        "`# godot_extension: register_class_hook` only allows static method"
                    )
                if signature.parameters or signature.return_type != "void":
                    raise RuntimeError(
                        "`# godot_extension: register_class_hook` method must have no parameter and return void"
                    )

                current_class.register_class_hook = signature.method_name

            def _unregister_class_hook() -> None:
                if current_class is None:
                    raise RuntimeError(
                        "`# godot_extension: unregister_class_hook` must be within a `# godot_extension: class(...)` pragma"
                    )

                if current_class.unregister_class_hook is not None:
                    raise RuntimeError(
                        "`# godot_extension: unregister_class_hook` can only be set once per `# godot_extension: class(...)` pragma"
                    )

                signature = _collect_method_signature()
                if not signature.is_staticmethod:
                    raise RuntimeError(
                        "`# godot_extension: unregister_class_hook` only allows static method"
                    )
                if signature.parameters or signature.return_type != "void":
                    raise RuntimeError(
                        "`# godot_extension: unregister_class_hook` method must have no parameter and return void"
                    )

                current_class.unregister_class_hook = signature.method_name

            def _cinit_instance_hook() -> None:
                if current_class is None:
                    raise RuntimeError(
                        "`# godot_extension: cinit_instance_hook` must be within a `# godot_extension: class(...)` pragma"
                    )

                if current_class.cinit_instance_hook is not None:
                    raise RuntimeError(
                        "`# godot_extension: cinit_instance_hook` can only be set once per `# godot_extension: class(...)` pragma"
                    )

                signature = _collect_method_signature()
                if signature.is_staticmethod:
                    raise RuntimeError(
                        "`# godot_extension: cinit_instance_hook` only allows non-static method"
                    )
                if signature.parameters or signature.return_type != "void":
                    raise RuntimeError(
                        "`# godot_extension: cinit_instance_hook` method must only have `self` as parameter and return void"
                    )

                current_class.cinit_instance_hook = signature.method_name

            def _free_instance_hook() -> None:
                if current_class is None:
                    raise RuntimeError(
                        "`# godot_extension: free_instance_hook` must be within a `# godot_extension: class(...)` pragma"
                    )

                if current_class.free_instance_hook is not None:
                    raise RuntimeError(
                        "`# godot_extension: free_instance_hook` can only be set once per `# godot_extension: class(...)` pragma"
                    )

                signature = _collect_method_signature()
                if signature.is_staticmethod:
                    raise RuntimeError(
                        "`# godot_extension: free_instance_hook` only allows non-static method"
                    )
                if signature.parameters or signature.return_type != "void":
                    raise RuntimeError(
                        "`# godot_extension: free_instance_hook` method must only have `self` as parameter and return void"
                    )

                current_class.free_instance_hook = signature.method_name

            def _method(const: bool = False, virtual: bool = False) -> None:
                if current_class is None:
                    raise RuntimeError(
                        "`# godot_extension: method(...)` must be within a `# godot_extension: class(...)` pragma"
                    )

                if not isinstance(const, bool):
                    raise RuntimeError("`const` parameter must be a boolean")
                is_const = const

                if not isinstance(virtual, bool):
                    raise RuntimeError("`virtual` parameter must be a boolean")
                is_virtual = virtual

                signature = _collect_method_signature()
                signature.is_const = is_const
                signature.is_virtual = is_virtual

                current_class.methods.append(signature)

            def _class(
                parent: str,
                is_virtual: bool = False,
                is_abstract: bool = False,
                is_exposed: bool = True,
            ) -> None:
                nonlocal current_class
                nonlocal classes

                if not isinstance(parent, str):
                    raise RuntimeError("`parent` parameter must be a string")

                try:
                    class_def_at_line, line1 = next(code_lines)
                    _, line2 = next(code_lines)

                    match = CLASS_RE.match(line2)
                    if line1.strip() != "@cython.final" or not match:
                        raise RuntimeError("expected `@cython.final` decorated cdef class")

                except StopIteration:
                    raise RuntimeError("unexpected end of file")

                current_class = ClassDef(
                    class_def_at_line=class_def_at_line,
                    class_name=match.group("class_name"),
                    parent_class_name=parent,
                    is_virtual=is_virtual,
                    is_abstract=is_abstract,
                    is_exposed=is_exposed,
                    methods=[],
                    inject_code_at_line=-1,
                    register_class_hook=None,
                    unregister_class_hook=None,
                    cinit_instance_hook=None,
                    free_instance_hook=None,
                )
                classes.append(current_class)

            try:
                eval(
                    "_" + pragma,
                    {
                        "_register_class_hook": _register_class_hook,
                        "_unregister_class_hook": _unregister_class_hook,
                        "_method": _method,
                        "_class": _class,
                        "_cinit_instance_hook": _cinit_instance_hook,
                        "_free_instance_hook": _free_instance_hook,
                    },
                )
            except NameError as exc:
                raise RuntimeError(f"Line {i + 1}: Unknown pragma `{line.strip()}`") from exc
            except Exception as exc:
                raise RuntimeError(
                    f"Line {i + 1}: Invalid pragma `{line.strip()}` ({exc})"
                ) from exc

    for klass in classes:
        if klass.inject_code_at_line == -1:
            raise RuntimeError(
                f"Line {klass.class_def_at_line}: Missing pragam `# godot_extension: {INJECT_CLASS_CODE_PRAGMA}` for class `{klass.class_name}`"
            )
        if inject_module_code_at_line == -1:
            raise RuntimeError(
                f"A `# godot_extension: {INJECT_MODULE_CODE_PRAGMA}` must be defined at module level to be able to use `# godot_extension: {INJECT_CLASS_CODE_PRAGMA}`"
            )

    return ModuleDef(
        inject_module_code_at_line=inject_module_code_at_line,
        classes=classes,
    )


def parse_code(code: str) -> str:
    # First pass: remove old autogenerate code if any
    iter_lines = enumerate(code.splitlines())
    code_lines = []
    currently_in_autogenerated_code = False
    for i, line in iter_lines:
        match = PRAGMA_RE.match(line)
        if match:
            pragma = match.group("pragma").strip()
            if pragma == AUTOGENERATED_HEADER:
                if currently_in_autogenerated_code:
                    raise RuntimeError(f"Line {i + 1}: Nested autogenerated header are not allowed")
                currently_in_autogenerated_code = True
                continue
            elif pragma == AUTOGENERATED_FOOTER:
                if not currently_in_autogenerated_code:
                    raise RuntimeError(
                        f"Line {i + 1}: Found autogenerated footer without matching header"
                    )
                currently_in_autogenerated_code = False
                continue

        if not currently_in_autogenerated_code:
            code_lines.append(line)

    # Second pass: find `# godot_extension: ...` pragma instructions
    spec = extract_classes_from_code(code_lines)

    # Last pass: inject generated code in the `# godot_extension: inject_code_site` pragmas

    # Order by injection line
    injection_order = reversed(
        sorted(
            [
                (spec.inject_module_code_at_line, None),
                *((klass.inject_code_at_line, klass) for klass in spec.classes),
            ]
        )
    )
    for inject_code_at_line, klass in injection_order:
        assert inject_code_at_line != -1

        if klass is None:
            injected_code = generate_injected_module_code(spec)
            indent = ""

        else:
            injected_code = generate_injected_class_code(klass)
            indent = "    "

        code_lines = (
            code_lines[: inject_code_at_line + 1]
            + [
                f"{indent}# godot_extension: {AUTOGENERATED_HEADER}",
                injected_code,
                f"{indent}# godot_extension: {AUTOGENERATED_FOOTER}",
            ]
            + code_lines[inject_code_at_line + 1 :]
        )

    code = "\n".join(code_lines)
    if not code.endswith("\n"):
        code += "\n"
    return code


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Godot extension class boilerplate for Cython code"
    )
    parser.add_argument(
        "input",
        type=Path,
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
    )
    parser.add_argument(
        "--debug",
        action="store_true",
    )
    args = parser.parse_args()
    if args.input.suffix not in (".pyx", ".pxi"):
        raise SystemExit("Expected .pyx/.pxi file as input")

    input_code = args.input.read_text(encoding="utf8")
    try:
        output_code = parse_code(input_code)
    except RuntimeError as exc:
        if args.debug:
            raise
        else:
            raise SystemExit(str(exc)) from exc
    if args.output:
        args.output.write_text(output_code, encoding="utf8")
    else:
        args.input.write_text(output_code, encoding="utf8")
