# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_bindings.py`

from godot._hazmat.gdnative_api_struct cimport *
from godot._hazmat.gdapi cimport pythonscript_gdapi10 as gdapi10
from godot.builtins cimport *

{% from 'class.tmpl.pxd' import render_class_pxd -%}
{%- for cls in classes %}
{{ render_class_pxd(cls) }}
{%- endfor %}

cdef void _initialize_bindings()
