{%- from 'builtin.tmpl.pxi' import render_spec -%}
# /!\ Autogenerated code, modifications will be lost /!\
# see `generation/generate_builtins.py`

cimport cython
from libc.math cimport INFINITY as inf  # Needed by some constants

from godot._hazmat.gdnative_interface cimport *
from godot._hazmat.gdapi cimport gdapi

{% for item in specs -%}
{{     render_spec(item) }}
{% endfor %}
