#! /bin/sh

CLANG_FORMAT=clang-format
ROOT_DIR=$(dirname `readlink -f "$0"`)/..

cd $ROOT_DIR

# cffi_bindings folder is full of autogenerated, don't check it
FILES=`git ls-files | grep -e '^pythonscript/\w\+\.\(cpp\|h\)$'`

$CLANG_FORMAT -i -style=file  $FILES
